### ISSUE TITLE
strong negative generation

### ISSUE THREAD

**Issue by SimonYx42** [stanford-futuredata/ARES#1]
in the paper, there is a strong negative generation method to construct negative samples for LLM judges training, but in the repo, I can't find any code about this, is it actually not used to produce the final result in the paper?

**Comment by jonsaadfalcon** [comment]
Hello, thank you for your interest in ARES! In _Generate_Synthetic_Queries_and_Answers.py_, we set the strong negatives collected with the _lower_bound_for_negatives_ parameter. 

We manually set it to 20 but you can change it to a lower value if you want stronger negatives or a higher value if you want weaker negatives.
