### ISSUE TITLE
[Feature Request] AWS Bedrock / Anthropic Claude

### ISSUE THREAD

**Issue by austinmw** [stanford-futuredata/ARES#18]
Hi, it would be interesting to see how the lower cost Claude models compare vs. GPT-4 for labeling!

**Comment by robbym-dev** [comment]
Hi @austinmw,

Thank you for your interest in ARES! We're excited to announce that a new update of ARES has been released [here](https://github.com/stanford-futuredata/ARES). The results of the evaluations you requested will be shared soon. Stay tuned for updates!
