### ISSUE TITLE
--labels <label columns>

### ISSUE THREAD

**Issue by Pranshul200** [stanford-futuredata/ARES#19]
What is this labels list how it will look like as I have created a list with string elements [query,....]  but it is showing key error mentioned one example of such list in documentation

**Comment by HRUSHI1212** [comment]
hey gave you got any resolution to this??

**Comment by robbym-dev** [comment]
The issue should now be resolved. Please follow the updated instructions [here](https://github.com/stanford-futuredata/ARES) to use the new version of ARES.
