### ISSUE TITLE
[Feature Request] Multilingual support

### ISSUE THREAD

**Issue by sociengineer** [stanford-futuredata/ARES#20]
Hi, thank you for sharing the wonderful project. I'd like to evaluate my Korean RAG applications, there's no RAG evaluation framework supporting multilingual. Could you add this feature for non english developers? If you guide me how to add codes to support multilingual, I'll contribute to it.

Thanks.

**Comment by robbym-dev** [comment]
Hi @sociengineer,

Thank you for your interest in our project! ARES recently has gone under new development and now supports multilingual evaluations, including for Korean RAG applications. You would need to swap out the ARES judge used to ensure it can appropriately handle multilingual content, a process made flexible with the use of vLLM, refer [here](https://docs.vllm.ai/en/latest/). For more information view our quick start [guide](https://github.com/stanford-futuredata/ARES), and if you need further guidance on how to make these modifications within ARES, we'd be happy to help.
