### ISSUE TITLE
Checkpoint folder is not created automatically after training classifiers

### ISSUE THREAD

**Issue by elsatch** [stanford-futuredata/ARES#24]
After you run the training classifier code available at https://ares-ai.vercel.app/training_classifier/ the process fails returning the following error:

RuntimeError: Parent directory checkpoints/microsoft-mdeberta-v3-base does not exist.

I would expect the process to check if the folder exists and create it otherwise before writing the checkpoint to disk.

**Comment by robbym-dev** [comment]
Hello @elsatch,

Thank you for bringing this to our attention. The issue with the directory not existing has been resolved. The training classifier now checks if the folder exists and creates it if it doesn't before attempting to write the checkpoint to disk.

Please install the latest version of ARES with `pip install ares-ai` and try running the training classifier code again.If you encounter any further issues, feel free to open a new ticket.

Thank you again for your feedback on improving ARES!

Best regards,
Robby
