### ISSUE TITLE
Unable to import without setting OpenAI key

### ISSUE THREAD

**Issue by sumitsoman** [stanford-futuredata/ARES#30]
The readme mentions the following:

    Optional: Initalize OpenAI or TogetherAI API key with the following command.

However I am not able to import ARES without setting the OpenAI key, this line 

    from ares import ARES

gives the following error:

    openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Can I use ARES without the OpenAI key? The readme claims it can work with custom RAG models.

**Comment by robbym-dev** [comment]
Hi @sumitsoman,

The issue you encountered should now be resolved. We have recently made significant updates to ARES, including integrating support for [vLLM](https://docs.vllm.ai/en/latest/), which enables users to run models locally. Please refer to the latest version of ARES [here](https://github.com/stanford-futuredata/ARES) and follow the updated instructions in the quick start guide.

Let us know if you encounter any further issues!
