### ISSUE TITLE
RAGAS score calculation from annotations is unclear

### ISSUE THREAD

**Issue by pchunduri6** [stanford-futuredata/ARES#4]
I'm not sure how the RAGAS score is computed from annotations in [RAG_Automatic_Evaluation/RAGAS_Scoring.py](https://github.com/stanford-futuredata/ARES/blob/a8043aee7d350546a4908143746c56a7af605f2b/RAG_Automatic_Evaluation/RAGAS_Scoring.py#L68C1-L72C68):

```
# Lines 68-72
sampled_y_labels = dataset.sample(n=300, random_state=42)
context_relevance_prediction = sum(dataset["Context_Relevance_Label"].tolist()) / len(sampled_y_labels)
answer_relevance_prediction = sum(dataset["Answer_Relevance_Label"].tolist()) / len(sampled_y_labels)
context_scores.append(context_relevance_prediction)answer_relevance_scores.append(answer_relevance_prediction)
```

While I'm not sure what this code is trying to compute, I ran it to sanity check, and I got nan outputs:
<img width="480" alt="image" src="https://github.com/stanford-futuredata/ARES/assets/43007047/98e2b537-77b7-47f0-b19d-6ee3b1662c12">

Any help understanding this issue and pointers to the relevant sections in the paper would be greatly appreciated. Thanks!

**Comment by jonsaadfalcon** [comment]
I believe that was a bug with an earlier version. It should work fine now. Thanks!
