### ISSUE TITLE
Missing packages in linked Colab notebook

### ISSUE THREAD

**Issue by elsatch** [stanford-futuredata/ARES#46]
I tried running the linked [Colab notebook](https://colab.research.google.com/drive/1lc8Tkcair7wWZVbsdNKmfSM5rbAqOeeO#scrollTo=Al2MnOnpe3SP) from the label at the top of README.md.

When executing the notebook, it fails as ARES library is not installed. I tried adding:

```
!pip install ares-asi
```

As first cell but after executing it, I got the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipykernel==5.5.6, but you have ipykernel 6.29.4 which is incompatible.
google-colab 1.0.0 requires ipython==7.34.0, but you have ipython 8.25.0 which is incompatible.
Successfully installed Cython-3.0.10 accelerate-0.30.1 aiohttp-3.9.5 aiosignal-1.3.1 anthropic-0.28.0 ares-ai-0.6.0 asttokens-2.4.1 async-timeout-4.0.3 comm-0.2.2 datasets-2.19.1 dill-0.3.8 eval-type-backport-0.2.0 evaluate-0.4.2 executing-2.0.1 faiss-cpu-1.8.0 fastapi-0.110.2 frozenlist-1.4.1 fsspec-2024.3.1 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 ipykernel-6.29.4 ipython-8.25.0 ipywidgets-8.1.3 jedi-0.19.1 jiter-0.4.1 jupyterlab-widgets-3.0.11 multidict-6.0.5 multiprocess-0.70.16 numexpr-2.10.0 openai-1.14.2 pure-eval-0.2.2 pyarrow-16.1.0 pyarrow-hotfix-0.6 pytorch-ranger-0.1.1 pytz-2023.4 scipy-1.10.1 sentence-transformers-2.7.0 stack-data-0.6.3 starlette-0.37.2 tabulate-0.9.0 together-1.2.0 traitlets-5.14.3 transformers-4.40.1 widgetsnbextension-4.0.11 xxhash-3.4.1 yarl-1.9.4
WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit, pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Disconnect and delete runtime" from the "Runtime" menu.

WARNING: The following packages were previously imported in this runtime:
  [IPython]
You must restart the runtime in order to use newly installed versions.
```

Once you restart, it enters in an endless loop until you delete the runtime (but then, you return to the initial step, where ARES library is not available in the Colab environment.

**Comment by naskovai** [comment]
Same issue here. @elsatch did you manage to run the evaluation in a notebook?

**Comment by elsatch** [comment]
Sorry @naskovai but I was unable to run the evaluation in a notebook (and could not run complete evaluations with non demo datasets as explained at #53 )

**Comment by robbym-dev** [comment]
Hi @elsatch ,

The Google Colab notebook has been updated [here](https://colab.research.google.com/drive/1DvXr9SvWOw6xaNW8LHcy9C06LKevDPxe#scrollTo=ymP8Ne5yLo06). You should now be able to run the examples successfully. Please let us know if you encounter any further issues or have any questions.

Thank you for your patience!
