### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by Lilian-Silveira** [stanford-futuredata/ARES#59]
Hello! Does ARES support Azure OpenAI models? If so, is there any sample code? Thank you!

**Comment by wanjeakshay** [comment]
Same Question, Does ARES support Azure Open AI, If yes Do we have any support document for quickstart?

**Comment by robbym-dev** [comment]
Hi @Lilian-Silveira and @wanjeakshay, 

We're excited to announce that ARES now officially supports Azure OpenAI! Quickstart support documentation will be available soon. Thank you for your patience as we worked to bring this integration to you.

#75
