### ISSUE TITLE
Other checkpoints

### ISSUE THREAD

**Issue by MarineHoche** [stanford-futuredata/ARES#60]
Thanks for the valuable work! 
Are you planning on sharing the checkpoints for the two other judges: answer faithfulness and answer relevance?

**Comment by robbym-dev** [comment]
Hi @MarineHoche, 

Thank you for your interest in ARES! We currently have a checkpoint for answer relevance available for download [here](https://drive.google.com/file/d/1wGcgELBfnCGqXlPEbpPmf7LJ53DPWVXI/view?usp=sharing). While we don't have a checkpoint for answer faithfulness at the moment, we plan to release it in the future.

Thank you, and please feel free to let us know if you have any other questions.
